// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/solo-dashboard/CurrentDashboard.tsx": () => import("../components/mockups/solo-dashboard/CurrentDashboard.tsx"),
  "./components/mockups/solo-dashboard/ProjectOverview.tsx": () => import("../components/mockups/solo-dashboard/ProjectOverview.tsx"),
  "./components/mockups/solo-dashboard/WeeklyPlanner.tsx": () => import("../components/mockups/solo-dashboard/WeeklyPlanner.tsx"),
  "./components/mockups/solo-landing/Current.tsx": () => import("../components/mockups/solo-landing/Current.tsx"),
  "./components/mockups/solo-landing/IndependentMaker.tsx": () => import("../components/mockups/solo-landing/IndependentMaker.tsx"),
  "./components/mockups/solo-landing/WorkingStudio.tsx": () => import("../components/mockups/solo-landing/WorkingStudio.tsx")
};
